# Generated by Django 4.2.5 on 2023-09-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Senior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(default='default/user.jpg', upload_to='senious/')),
                ('capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(default='default/sm-3.jpg', upload_to='hero_images/'),
        ),
    ]
