# Generated by Django 4.2.5 on 2023-09-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_senior_alter_hero_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(default='default/default_logo.png', upload_to='company_logos/')),
                ('banner_image', models.ImageField(default='default/default_banner.jpg', upload_to='company_banners/')),
                ('description', models.TextField()),
                ('website', models.URLField()),
                ('headquarters', models.CharField(max_length=255)),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='senior',
            name='profile_pic',
            field=models.ImageField(default='default/user.jpg', upload_to='seniors/'),
        ),
    ]
