# Generated by Django 4.2.5 on 2023-09-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default='default/default_event.jpg', upload_to='event_images/'),
        ),
    ]
